name: Atualizar GitHub Readme Stats

on:
  schedule:
    - cron: '0 */6 * * *'  # A cada 6 horas
  workflow_dispatch:        # Roda manualmente
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Warming up GitHub Readme Stats cache
        run: |
          curl -s "https://github-readme-stats.vercel.app/api?username=vinichaves"
          curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=vinichaves"
